# Generated by Django 5.0 on 2023-12-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_enrty_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrty',
            name='authors',
            field=models.ManyToManyField(related_name='author', to='app1.author'),
        ),
    ]
