# Generated by Django 5.0 on 2023-12-18 13:36

import temptomodapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(help_text='Please Enter M for Male, F for Female', max_length=10, validators=[temptomodapp.models.gender_validate])),
                ('phone', models.CharField(max_length=50, validators=[temptomodapp.models.phone_verify])),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
