# Generated by Django 5.0 on 2023-12-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('emp_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('salary', models.FloatField(default=0.0)),
            ],
        ),
    ]
