# Generated by Django 5.0 on 2023-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField(verbose_name='AGE_of_fog')),
                ('password', models.CharField(help_text='Plesae enter more than 8 char', max_length=40)),
            ],
        ),
    ]
