# Generated by Django 5.0 on 2023-12-16 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='typeoffields',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 14, 58, 48, 376746)),
        ),
    ]
