# Generated by Django 5.0 on 2023-12-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0002_alter_stud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='age',
            field=models.IntegerField(db_column='AGE_of_fog'),
        ),
    ]
