# Generated by Django 5.0 on 2023-12-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0003_alter_stud_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='age',
            field=models.IntegerField(verbose_name='AGE_of_fog'),
        ),
    ]
