# Generated by Django 5.0 on 2023-12-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0003_stud_delete_employee_delete_staff_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
